coverage:
  ignore:
    - Carthage/*
    - Example/*
    - ExampleUITests/*
    - QuickTableViewControllerTests/*
    - Pods/*
  status:
    project:
      default:
        enabled: yes
        target: 80%
        threshold: 3%
